const Districts = [
  { name: "Ampara" },
  { name: "Anuradhapura" },
  { name: "Badulla" },
  { name: "Batticaloa" },
  { name: "Colombo" },
  { name: "Galle" },
  { name: "Gampaha" },
  { name: "Hambantota" },
  { name: "Jaffna" },
  { name: "Kalutara" },
  { name: "Kandy" },
  { name: "Kegalle" },
  { name: "Kilinochchi" },
  { name: "Kurunegala" },
  { name: "Mannar" },
  { name: "Matale" },
  { name: "Matara" },
  { name: "Monaragala" },
  { name: "Mullaitivu" },
  { name: "Nuwara Eliya" },
  { name: "Polonnaruwa" },
  { name: "Puttalam" },
  { name: "Ratnapura" },
  { name: "Trincomalee" },
  { name: "Vavuniya" },
];
const SearchDistricts = [
  { name: "--All Locations--" },
  { name: "Ampara" },
  { name: "Anuradhapura" },
  { name: "Badulla" },
  { name: "Batticaloa" },
  { name: "Colombo" },
  { name: "Galle" },
  { name: "Gampaha" },
  { name: "Hambantota" },
  { name: "Jaffna" },
  { name: "Kalutara" },
  { name: "Kandy" },
  { name: "Kegalle" },
  { name: "Kilinochchi" },
  { name: "Kurunegala" },
  { name: "Mannar" },
  { name: "Matale" },
  { name: "Matara" },
  { name: "Monaragala" },
  { name: "Mullaitivu" },
  { name: "Nuwara Eliya" },
  { name: "Polonnaruwa" },
  { name: "Puttalam" },
  { name: "Ratnapura" },
  { name: "Trincomalee" },
  { name: "Vavuniya" },
];
export { Districts, SearchDistricts };
